# Test parameters.
{{$NAMESPACES := DefaultParam .CL2_NAMESPACES 1}}

# Sleep time for manual configuration of the cluster, to ssh and update manifest if needed
{{$SLEEP_FOR_MANUAL_CONFIG := DefaultParam .CL2_SLEEP_FOR_MANUAL_CONFIG "0m"}}

# Creating 5,000 pods podAntiAffinity to trigger scaleup of 5k e2 nodes
{{$E2_PODS_SIZE := DefaultParam .CL2_E2_PODS_SIZE 5000}}
{{$E2_MEASUREMENT_TIMEOUT := DefaultParam .CL2_E2_MEASUREMENT_TIMEOUT "20m"}}

# Creating 100 pods in batches of 25 with podAntiAffinity to trigger scaleup of 100 ek nodes
# with 2 minute wait between each batch to allow downsize for the nodes
# Important Note: downsize-config should be set to an appropriate value at the job config
# to allow downsize of nodes within 2 minutes, otherwise the test will fail
{{$PODS_BATCH_SIZE := DefaultParam .CL2_PODS_BATCH_SIZE 4}}
{{$TOTAL_BATCHES_NUMBER := DefaultParam .CL2_TOTAL_BATCHES_NUMBER 25}}  # 4 * 25 = 100 pods
{{$BATCH_MEASUREMENT_TIMEOUT := DefaultParam .CL2_BATCH_MEASUREMENT_TIMEOUT "10m"}}
{{$BATCH_WAIT_DURATION := DefaultParam .CL2_BATCH_WAIT_DURATION "2m"}}

# Create 200 pods after setting-up the nodes to trigger upsize
{{$WAIT_BEFORE_UPSIZE := DefaultParam .CL2_WAIT_BEFORE_UPSIZE "10m"}}
{{$UPSIZE_PODS_COUNT := DefaultParam .CL2_UPSIZE_PODS_COUNT 200}}
{{$UPSIZE_MEASUREMENT_TIMEOUT := DefaultParam .CL2_UPSIZE_MEASUREMENT_TIMEOUT "10m"}}
{{$UPSIZE_THRESHOLD := DefaultParam .CL2_UPSIZE_THRESHOLD "10m"}}
{{$UPSIZE_PERC50_THRESHOLD := DefaultParam .CL2_UPSIZE_PERC50_THRESHOLD "40s"}}
{{$UPSIZE_PERC90_THRESHOLD := DefaultParam .CL2_UPSIZE_PERC90_THRESHOLD "4m"}}

name: ek-parallel-upsizes
namespace:
  number: {{$NAMESPACES}}
tuningSets:
- name: default
  globalQPSLoad:
    qps: 100
    burst: 1

steps:
- name: Waiting for {{$SLEEP_FOR_MANUAL_CONFIG}} before starting the test to allow manual configuration if needed
  measurements:
  - Identifier: WaitForManualConfig
    Method: Sleep
    Params:
      duration: {{$SLEEP_FOR_MANUAL_CONFIG}}

- name: Starting measurement for e2 deployment
  measurements:
  - Identifier: WaitForRunningE2Batch
    Method: WaitForControlledPodsRunning
    Params:
      action: start
      apiVersion: apps/v1
      kind: Deployment
      labelSelector: group = e2-scale-deployment
      operationTimeout: {{$E2_MEASUREMENT_TIMEOUT}}
      checkIfPodsAreUpdated: false

- name: Creating e2-deployment of {{$E2_PODS_SIZE}} pods
  phases:
  - namespaceRange:
      min: 1
      max: {{$NAMESPACES}}
    replicasPerNamespace: 1
    tuningSet: default
    objectBundle:
    - basename: e2-scale-test
      objectTemplatePath: e2-scale-deployment.yaml
      templateFillMap:
        Replicas: {{$E2_PODS_SIZE}}

- name: Waiting for e2-deployment to be running
  measurements:
  - Identifier: WaitForRunningE2Batch
    Method: WaitForControlledPodsRunning
    Params:
      action: gather

# Creating ($PODS_BATCH_SIZE * $TOTAL_BATCHES_NUMBER) pods in batches of $TOTAL_BATCHES_NUMBER with $BATCH_WAIT_DURATION minute wait between each batch with podAntiAffinity to trigger scaleup of nodes
{{range $batch := Loop $TOTAL_BATCHES_NUMBER }}
- name: Starting measurement for batch {{AddInt 1 $batch}}
  measurements:
  - Identifier: WaitForRunningBatch{{AddInt 1 $batch}}
    Method: WaitForControlledPodsRunning
    Params:
      action: start
      apiVersion: apps/v1
      kind: Deployment
      labelSelector: group = ek-scale-deployment
      operationTimeout: {{$BATCH_MEASUREMENT_TIMEOUT}}
      checkIfPodsAreUpdated: false

- name: Creating batch {{AddInt 1 $batch}} of pods
  phases:
  - namespaceRange:
      min: 1
      max: {{$NAMESPACES}}
    replicasPerNamespace: 1
    tuningSet: default
    objectBundle:
    - basename: ek-scale-test-{{AddInt 1 $batch}}
      objectTemplatePath: ek-scale-deployment.yaml
      templateFillMap:
        Replicas: {{$PODS_BATCH_SIZE}}

- name: Waiting for batch {{AddInt 1 $batch}} to be running
  measurements:
  - Identifier: WaitForRunningBatch{{AddInt 1 $batch}}
    Method: WaitForControlledPodsRunning
    Params:
      action: gather

- name: Waiting for {{$BATCH_WAIT_DURATION}} before creating next batch to allow downsize
  measurements:
  - Identifier: WaitBetweenBatches{{AddInt 1 $batch}}
    Method: Sleep
    Params:
      duration: {{$BATCH_WAIT_DURATION}}
{{end}}

# Wait 10 mins after the last batch to make sure if any extra node is processing is scaled-down
- name: Waiting for {{$WAIT_BEFORE_UPSIZE}} before starting upsize to allow scale down extra nodes
  measurements:
  - Identifier: WaitBeforeUpsize
    Method: Sleep
    Params:
      duration: {{$WAIT_BEFORE_UPSIZE}}

- name: Starting measurements for upsizing
  measurements:
  - Identifier: PodStartupLatency
    Method: PodStartupLatency
    Params:
      action: start
      labelSelector: group = ek-upsize-test
      perc50Threshold: {{$UPSIZE_PERC50_THRESHOLD}}
      perc90Threshold: {{$UPSIZE_PERC90_THRESHOLD}}
      threshold: {{$UPSIZE_THRESHOLD}}
  - Identifier: WaitForControlledPodsRunning
    Method: WaitForControlledPodsRunning
    Params:
      action: start
      apiVersion: apps/v1
      kind: Deployment
      labelSelector: group = ek-upsize-deployment
      operationTimeout: {{$UPSIZE_MEASUREMENT_TIMEOUT}}
      checkIfPodsAreUpdated: false

# Step to create the additional UPSIZE_PODS_COUNT pods without node affinity (1 CPU, 4 GB memory) to test upsize
- name: Creating {{$UPSIZE_PODS_COUNT}} additional pods (1 CPU, 4GB, no node affinity)
  phases:
  - namespaceRange:
      min: 1
      max: {{$NAMESPACES}}
    replicasPerNamespace: 1
    tuningSet: default
    objectBundle:
    - basename: ek-upsize-test
      objectTemplatePath: ek-upsize-deployment.yaml
      templateFillMap:
        Replicas: {{$UPSIZE_PODS_COUNT}}

- name: Waiting for {{$UPSIZE_PODS_COUNT}} additional pods to be scheduled
  measurements:
  - Identifier: WaitForControlledPodsRunning
    Method: WaitForControlledPodsRunning
    Params:
      action: gather

- name: Measure pod startup latency
  measurements:
  - Identifier: PodStartupLatency
    Method: PodStartupLatency
    Params:
      action: gather