apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}
type: Opaque
# This requires https://github.com/kubernetes/kubernetes/pull/85641 to be merged.
immutable: true
data:
  password: c2NhbGFiaWxpdHkK
