apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    group: saturation
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      app: app-{{.Index}}
  template:
    metadata:
      labels:
        app: app-{{.Index}}
        group: saturation
    spec:
      containers:
      - image: gcr.io/google-samples/whereami:v1.2.22
        imagePullPolicy: IfNotPresent
        name: {{.Name}}
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10M
      # Add not-ready/unreachable tolerations for 15 minutes so that node
      # failure doesn't trigger pod deletion.
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
