kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{.Name}}
spec:
  # To use a load-balancer based on Envoy proxies, e.g. an Internal Load
  # Balancer such as gke-l7-rilb, set up a network with a command such as the
  # one below.
  #
  # http://cloud/kubernetes-engine/docs/how-to/internal-load-balance-ingress#prepare-environment
  #
  # gcloud compute networks subnets create proxy-only-subnet
  #  --purpose=REGIONAL_MANAGED_PROXY
  #  --role=ACTIVE
  #  --region=us-central1                # Update if needed.
  #  --network=envoy-proxy-us-central1   # Subnet name.
  #  --range=10.127.0.0/16               # Update if needed.
  gatewayClassName: {{.GatewayClass}}
  listeners:
  - name: http
    protocol: HTTP
    port: 80
