{{$cpuRequest := DefaultParam .cpuRequest "5m"}}
{{$basename := DefaultParam .basename (printf "deployment-%.0f" .size)}}
{{$threshold := DefaultParam .throughputThreshold 0}}

steps:
- name: Starting measurements for deployments
  measurements:
  - Identifier: WaitForRunningDeployments
    Method: WaitForControlledPodsRunning
    Params:
      apiVersion: apps/v1
      kind: Deployment
      action: start
      labelSelector: group = load
      operationTimeout: 30m
{{if .create}}
- module:
    path: modules/scheduling-throughput.yaml
    params:
      basename: {{$basename}}
      action: start
      threshold: {{$threshold}}
- name: Creating services/configmaps for size {{.size}}
  phases:
  - namespaceRange:
      min: {{.minNamespace}}
      max: {{.maxNamespace}}
    replicasPerNamespace: 1
    tuningSet: Sequence
    objectBundle:
    - basename: {{$basename}}-svc
      objectTemplatePath: service.yaml
    - basename: {{$basename}}-cfm
      objectTemplatePath: configmap.yaml
      templateFillMap:
        Length: 10240 # 10 KiB
- name: Creating deployments of size {{.size}}
  phases:
  - namespaceRange:
      min: {{.minNamespace}}
      max: {{.maxNamespace}}
    replicasPerNamespace: 1
    tuningSet: default
    objectBundle:
    - basename: {{$basename}}
      objectTemplatePath: simple-deployment.yaml
      templateFillMap:
        Replicas: {{.size}}
        SvcName: {{$basename}}-svc
        ConfigMapName: {{$basename}}-cfm
        {{if .priorityClassName}}
        PriorityClassName: {{.priorityClassName}}
        {{end}}
        CpuRequest: {{$cpuRequest}}
- name: Waiting for 'create' to be completed
  measurements:
  - Method: WaitForControlledPodsRunning
    Identifier: WaitForRunningDeployments
    Params:
      action: gather
- module:
    path: modules/scheduling-throughput.yaml
    params:
      basename: {{$basename}}
      action: gather
{{end}}

{{if .update}}
# We do not need to change templateFillMap as env variable for pod is randomly generated.
- name: Updating deployments of size {{.size}}
  phases:
  - namespaceRange:
      min: {{.minNamespace}}
      max: {{.maxNamespace}}
    replicasPerNamespace: 1
    tuningSet: default
    objectBundle:
    - basename: {{$basename}}
      objectTemplatePath: simple-deployment.yaml
      templateFillMap:
        Replicas: {{.size}}
        SvcName: {{$basename}}-svc
        ConfigMapName: {{$basename}}-cfm
        {{if .priorityClassName}}
        PriorityClassName: {{.priorityClassName}}
        {{end}}
        CpuRequest: {{$cpuRequest}}
- name: Waiting for 'update' to be completed
  measurements:
  - Method: WaitForControlledPodsRunning
    Identifier: WaitForRunningDeployments
    Params:
      action: gather
{{end}}

{{if .delete}}
- name: Deleting deployments of size {{.size}}
  phases:
  - namespaceRange:
      min: {{.minNamespace}}
      max: {{.maxNamespace}}
    replicasPerNamespace: 0
    tuningSet: default
    objectBundle:
    - basename: {{$basename}}
      objectTemplatePath: simple-deployment.yaml
- name: Waiting for 'delete' to be completed
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningDeployments
    Params:
      action: gather
- name: Deleting services/configmaps for size {{.size}}
  phases:
  - namespaceRange:
      min: {{.minNamespace}}
      max: {{.maxNamespace}}
    replicasPerNamespace: 0
    tuningSet: Sequence
    objectBundle:
    - basename: {{$basename}}-svc
      objectTemplatePath: service.yaml
    - basename: {{$basename}}-cfm
      objectTemplatePath: configmap.yaml
{{end}}
