apiVersion: v1
kind: Pod
metadata:
  name: {{.Name}}
  labels:
    group: {{.Group}}
spec:
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.1
    resources:
      requests:
        cpu: {{.CpuRequest}}
        memory: {{.MemRequest}}