- target: "https://localhost:10250/metrics/resource"
  job: "kubelet-resource"
  trimmedmetrics:
  - "container_start_time_seconds"
  - "container_cpu_usage_seconds_total"
  - "container_memory_working_set_bytes"
- target: "http://localhost:2379/metrics"
  job: "etcd:2379"
- target: "http://localhost:2382/metrics"
  job: "etcd:2382"
- target: "http://localhost:8942/metrics"
  job: "vpa-recommender"
- target: "https://localhost:10257/metrics"
  job: "kube-controller-manager"
- target: "https://localhost:10259/metrics"
  job: "kube-scheduler"
- target: "https://localhost:10260/metrics"
  job: "cloud-controller-manager"
- target: "http://localhost:8812/metrics"
  job: "auto-gke-billing"
- target: "http://localhost:8086/metrics"
  job: "l7-lb-controller"
- target: "http://localhost:8085/metrics"
  job: "cluster-autoscaler"
- target: "http://localhost:3381/metrics"
  job: "kspan-proxy"
  trimmedmetrics:
  - "kspan_proxy_shadow_status"
- target: "http://localhost:3481/metrics"
  job: "kspan-proxy-shadow"
  trimmedmetrics:
  - "kspan_proxy_shadow_status"
- target: "http://localhost:2022/metrics"
  job: "customer-logs-exporter"
- target: "https://localhost:443/metrics"
  job: "apiserver"
