{{$tuningSet := .tuningSet}}

{{$namespaces := .namespaces}}
{{$smallConfigMapCount := .smallConfigMapCount}}
{{$smallSecretCount := .smallSecretCount}}

steps:
- name: Small configmaps
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    tuningSet: {{$tuningSet}}
    replicasPerNamespace: {{$smallConfigMapCount}}
    objectBundle:
    - basename: small-configmap
      objectTemplatePath: small-configmap.yaml

- name: Small secrets
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    tuningSet: {{$tuningSet}}
    replicasPerNamespace: {{$smallSecretCount}}
    objectBundle:
    - basename: small-secret
      objectTemplatePath: small-secret.yaml
