// Package main this is a fake comment.
package main

import (
	"encoding/json"
	"flag"
	"log"
	"os"

	"gke-internal.googlesource.com/test-infra/perf-tests/testing/twitter/overrides/cronjobs"
	"gke-internal.googlesource.com/test-infra/perf-tests/testing/twitter/overrides/microservices"
	"gke-internal.googlesource.com/test-infra/perf-tests/testing/twitter/overrides/namespaces"
	"gke-internal.googlesource.com/test-infra/perf-tests/testing/twitter/overrides/secrets"
	"gke-internal.googlesource.com/test-infra/perf-tests/testing/twitter/overrides/statefulsets"
	"gke-internal.googlesource.com/test-infra/perf-tests/testing/twitter/overrides/updates"

	"gopkg.in/yaml.v2"
)

var (
	cronjobSpec        = flag.String("cronjobs", "", "A path to json file with cronjob spec")
	microserviceSpec   = flag.String("microservices", "", "A path to json file with microservices spec")
	updatesSpec        = flag.String("updates", "", "A path to json file with updates spec")
	nsDistributionSpec = flag.String("ns-distribution", "", "A path to json file with namespaces dist spec")
	out                = flag.String("out", "", "A path where output file will be created")
)

// TestSpec this is a fake comment.
type TestSpec struct {
	Cronjobs      *cronjobs.Spec
	Microservices *microservices.Spec
	Secrets       []secrets.Secret
	Updates       *updates.Spec
	StatefulSets  []statefulsets.Spec
	Distribution  *namespaces.Spec
}

// MarshalYAML this is a fake comment.
func (t *TestSpec) MarshalYAML() (interface{}, error) {
	return map[string]interface{}{
		"CRONJOBS":      t.Cronjobs.HealthyCrons,
		"MICROSERVICES": t.Microservices.HealthyServices,
		"SECRETS":       t.Secrets,
		"STATEFULSETS":  t.StatefulSets,
	}, nil
}

func readJSON(fileName string, out interface{}) error {
	f, err := os.Open(fileName)
	if err != nil {
		return err
	}
	defer f.Close()
	d := json.NewDecoder(f)
	return d.Decode(&out)
}

func main() {
	flag.Parse()

	if *cronjobSpec == "" || *microserviceSpec == "" || *updatesSpec == "" || *nsDistributionSpec == "" || *out == "" {
		log.Fatal("--cronjobs, --microservices, --updates, --distribution and --out are required arguments")
	}

	var spec TestSpec
	var err error
	if err := readJSON(*cronjobSpec, &spec.Cronjobs); err != nil {
		log.Fatalf("error while parsing cronjobs spec in %q: %v", *cronjobSpec, err)
	}
	if err := readJSON(*microserviceSpec, &spec.Microservices); err != nil {
		log.Fatalf("error while parsing microservices spec in %q: %v", *microserviceSpec, err)
	}
	if err := readJSON(*updatesSpec, &spec.Updates); err != nil {
		log.Fatalf("error while parsing updates spec in %q: %v", *updatesSpec, err)
	}
	if err := readJSON(*nsDistributionSpec, &spec.Distribution); err != nil {
		log.Fatalf("error while parsing namespaces spec in %q: %v", *nsDistributionSpec, err)
	}

	if err = cronjobs.Transform(spec.Cronjobs, spec.Distribution.Cronjobs); err != nil {
		log.Fatalf("error while transforming cronjobs: %v", err)
	}
	if err = microservices.Transform(spec.Microservices, spec.Distribution.Services); err != nil {
		log.Fatalf("error while transforming services: %v", err)
	}

	if err := updates.Schedule(spec.Updates, spec.Microservices); err != nil {
		log.Fatalf("error while scheduling updates: %v", err)
	}
	if spec.Secrets, err = secrets.Attach(spec.Distribution.Secrets, spec.Microservices); err != nil {
		log.Fatalf("error while generating secrets: %v", err)
	}
	if spec.StatefulSets, err = statefulsets.Generate(); err != nil {
		log.Fatalf("error while generating statefulsets: %v", err)
	}

	f, err := os.OpenFile(*out, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0755)
	if err != nil {
		log.Fatalf("error while opening a file: %v", err)
	}
	defer f.Close()

	if _, err := f.Write([]byte("#### AUTOGENERATED FILE -- DO NOT EDIT MANUALLY ####\n")); err != nil {
		log.Fatalf("error while writing preamble to output: %v", err)
	}
	e := yaml.NewEncoder(f)
	if err = e.Encode(&spec); err != nil {
		log.Fatalf("error while encoding output: %v", err)
	}
	defer e.Close()
}
