---
# Source: tpu-dra-driver/templates/kubeletplugin.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tpu-dra-driver-kubeletplugin
  namespace: {{.Namespace}}
  labels:
    helm.sh/chart: tpu-dra-driver-0.1.0
    app.kubernetes.io/name: tpu-dra-driver
    app.kubernetes.io/instance: tpu-dra-driver
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tpu-dra-driver
      app.kubernetes.io/instance: tpu-dra-driver
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tpu-dra-driver
        app.kubernetes.io/instance: tpu-dra-driver
    spec:
      hostNetwork: true
      serviceAccountName: tpu-dra-driver-service-account
      securityContext:
        {}
      initContainers:
      - name: "tpu-network-optimization"
        image: "gcr.io/gke-release/tpu_network_optimizer:tpu_network_optimizer_20250625.00_p0@sha256:0404b7f8ce86b25284a844ee4935c8927cd2572c1d6b07d1d2bd944f215fb80d"
        securityContext:
          privileged: true
        command:
        - /tpu_network_optimizer.sh
        volumeMounts:
        - name: sys
          mountPath: /sys
        - name: proc
          mountPath: /proc
      containers:
      - name: tpu-dra-plugin
        securityContext:
          privileged: true
        image: gcr.io/gke-scalability-images/tpu-dra/tpu-dra-driver:v1.0.0-gke.7
        imagePullPolicy: Always
        command: ["tpu-dra-kubeletplugin"]
        resources:
          {}
        env:
        - name: CDI_ROOT
          value: /var/run/cdi
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DEVICE_CLASSES
          value: tpu
        - name: CLUSTER_PROJECT                  # for testing purposes
          value: "484732669778"
        - name: CLUSTER_LOCATION                 # for testing purposes
          value: "us-central2-b"
        - name: CLUSTER_NAME                     # for testing purposes
          value: "sriyaganti-tpu-dra-cluster"
        - name: CONTAINER_NAME                   # for testing purposes
          value: "tpu-dra-plugin"
        - name: CLOUD_MONITORING_ENDPOINT        # for testing purposes
          value: "monitoring.googleapis.com:443"
        volumeMounts:
        - name: plugins-registry
          mountPath: /var/lib/kubelet/plugins_registry
        - name: plugins
          mountPath: /var/lib/kubelet/plugins
        - name: cdi
          mountPath: /var/run/cdi
        - name: sys
          mountPath: /sys
        - name: proc
          mountPath: /proc
        - name: pod-resources
          mountPath: /var/lib/kubelet/pod-resources
        - name: tpu-logs
          mountPath: /tmp/tpu_logs
      - name: sidecar-log-collector
        image: "gcr.io/gke-release/gke-distroless/bash:gke_distroless_20250807.00_p0@sha256:4de2c75a1f363c26c4f74bdd702d313410267c464a059b4fa32ac5d4cf10aba9"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
          limits:
            memory: 20Mi
        args: [/bin/sh, -c, '
          tail -n+1 -F /tmp/tpu_logs/tpu_driver.INFO & pid=$!;
          trap "kill -15 $pid; wait $pid" SIGTERM;
          wait $pid;
          ']
        volumeMounts:
        - name: tpu-logs
          readOnly: true
          mountPath: /tmp/tpu_logs
      - name: vbar-control-agent
        image: "gcr.io/gke-release/vbar_control_agent@sha256:631a35b6cc0638b3eed328ccea240199043dcfe4bed69c7cfc3d98752faa23fb"
        env:
        - name: TPU_SKIP_MDS_QUERY
          value: 'true'
        - name: TPU_ON_GKE
          value: 'true'
        securityContext:
          privileged: true
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            memory: 150Mi
            cpu: 10m
          limits:
            memory: 150Mi
        command: ["vbar_control_agent_files/bin/vbar_control_agent"]
        args: ['--logtostderr', '--census_enabled=false', '--gid=', '--uid=', '--chroot=']
      volumes:
      - name: plugins-registry
        hostPath:
          path: /var/lib/kubelet/plugins_registry
      - name: plugins
        hostPath:
          path: /var/lib/kubelet/plugins
      - name: cdi
        hostPath:
          path: /var/run/cdi
      - name: dev
        hostPath:
          path: /dev
          type: DirectoryOrCreate
      - name: pod-resources
        hostPath:
          path: /var/lib/kubelet/pod-resources
          type: DirectoryOrCreate
      - name: tpu-env
        hostPath:
          path: /etc/tpu
          type: DirectoryOrCreate
      - name: tpu-logs
        hostPath:
          path: /tmp/tpu_logs
          type: DirectoryOrCreate
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      - name: proc
        hostPath:
          path: /proc
          type: Directory
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-tpu-accelerator
                operator: Exists
              - key: gke-no-default-tpu-device-plugin
                operator: In
                values:
                - "true"
      tolerations:
        - effect: NoSchedule
          key: google.com/tpu
          operator: Exists
