---
# Source: tpu-dra-driver/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tpu-dra-driver-service-account
  namespace: {{.Namespace}}
  labels:
    helm.sh/chart: tpu-dra-driver-0.1.0
    app.kubernetes.io/name: tpu-dra-driver
    app.kubernetes.io/instance: tpu-dra-driver
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm