# Test consts
{{$RESTART_COUNT_THRESHOLD_OVERRIDES:= DefaultParam .RESTART_COUNT_THRESHOLD_OVERRIDES ""}}

{{$NODE_COUNT_ERROR_MARGIN:= 150}} # 1% of total 15k nodes
{{$INITIAL_NODE_COUNT:= 6000}}
{{$PHASE1_NODE_COUNT:= 10000}}
{{$PHASE2_NODE_COUNT:= 14900}}
{{$OPERATION_TIMEOUT:= "60m"}}

name: bayer
namespace:
  number: 1
tuningSets:
- name: QpsTuningSet
  QpsLoad:
    qps: 1
steps:

- name: Starting measurements
  measurements:
  - Identifier: APIResponsivenessPrometheus
    Method: APIResponsivenessPrometheus
    Params:
      action: start
  - Identifier: InClusterNetworkLatency
    Method: InClusterNetworkLatency
    Params:
      action: start
      replicasPerProbe: {{AddInt 2 (DivideInt .Nodes 100)}}
  - Identifier: DnsLookupLatency
    Method: DnsLookupLatency
    Params:
      action: start
      replicasPerProbe: {{AddInt 2 (DivideInt .Nodes 100)}}
  - Identifier: TestMetrics
    Method: TestMetrics
    Params:
      action: start
      systemPodMetricsEnabled: true
      restartCountThresholdOverrides: {{YamlQuote $RESTART_COUNT_THRESHOLD_OVERRIDES 4}}
      enableRestartCountCheck: true
  - Identifier: Quotas total usage
    Method: GenericPrometheusQuery
    Params:
      action: start
      metricName: Quota usage
      metricVersion: v1
      prometheusClient: managed
      unit: QPMs
      dimensions:
      - quota_metric
      queries:
      - name: perc99
        query: quantile_over_time(0.99, sum by (quota_metric) (irate(serviceruntime_googleapis_com:quota_rate_net_usage{monitored_resource="consumer_quota"}[1m]))[%v:]) * 60
      - name: max
        query: max_over_time(sum by (quota_metric) (irate(serviceruntime_googleapis_com:quota_rate_net_usage{monitored_resource="consumer_quota"}[1m]))[%v:]) * 60

- name: Starting measurement for waiting for pods
  measurements:
  - Identifier: WaitForRunningDeployments
    Method: WaitForControlledPodsRunning
    Params:
      action: start
      apiVersion: apps/v1
      kind: Deployment
      labelSelector: group = bayer
      operationTimeout: {{$OPERATION_TIMEOUT}}

# Whole test is just 1 deployment with 1 pod / node.
# Each pod uses same configmap. Note that the spec says:
# "Number of Secrets per configmap per pod: 1 secret per configmap per pod"
# This is a bit confusing (what does the secret per configmap mean?), but
# since the secrets and configmap are handled in a simmilar way by k8s, let's
# assume that we just have a single configmap.
- name: Creating {{$INITIAL_NODE_COUNT}} pods
  phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: 1
    tuningSet: QpsTuningSet
    objectBundle:
    - basename: configmap
      objectTemplatePath: configmap.yaml
    - basename: deployment
      objectTemplatePath: deployment.yaml
      templateFillMap:
        Replicas: {{$INITIAL_NODE_COUNT}}
- name: Waiting for pods to be running
  measurements:
  - Identifier: WaitForRunningDeployments
    Method: WaitForControlledPodsRunning
    Params:
      action: gather

- name: Scaling up to {{$PHASE1_NODE_COUNT}} pods
  phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: 1
    tuningSet: QpsTuningSet
    objectBundle:
    - basename: configmap
      objectTemplatePath: configmap.yaml
    - basename: deployment
      objectTemplatePath: deployment.yaml
      templateFillMap:
        Replicas: {{$PHASE1_NODE_COUNT}}
- name: Waiting for pods to be running
  measurements:
  - Identifier: WaitForRunningDeployments
    Method: WaitForControlledPodsRunning
    Params:
      action: gather

- name: Scaling up to {{$PHASE2_NODE_COUNT}} pods
  phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: 1
    tuningSet: QpsTuningSet
    objectBundle:
    - basename: configmap
      objectTemplatePath: configmap.yaml
    - basename: deployment
      objectTemplatePath: deployment.yaml
      templateFillMap:
        Replicas: {{$PHASE2_NODE_COUNT}}
- name: Waiting for pods to be running
  measurements:
  - Identifier: WaitForRunningDeployments
    Method: WaitForControlledPodsRunning
    Params:
      action: gather

- name: Scaling down to {{$PHASE1_NODE_COUNT}} pods
  phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: 1
    tuningSet: QpsTuningSet
    objectBundle:
    - basename: configmap
      objectTemplatePath: configmap.yaml
    - basename: deployment
      objectTemplatePath: deployment.yaml
      templateFillMap:
        Replicas: {{$PHASE1_NODE_COUNT}}
- name: Waiting for nodes and pods to be scaled down
  measurements:
  - Identifier: WaitForRunningDeployments
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
  - Identifier: WaitForNodes
    Method: WaitForNodes
    Params:
      minDesiredNodeCount: {{SubtractInt $PHASE1_NODE_COUNT $NODE_COUNT_ERROR_MARGIN}}
      maxDesiredNodeCount: {{AddInt $PHASE1_NODE_COUNT $NODE_COUNT_ERROR_MARGIN}}
      timeout: {{$OPERATION_TIMEOUT}}

- name: Scaling down to {{$INITIAL_NODE_COUNT}} pods
  phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: 1
    tuningSet: QpsTuningSet
    objectBundle:
    - basename: configmap
      objectTemplatePath: configmap.yaml
    - basename: deployment
      objectTemplatePath: deployment.yaml
      templateFillMap:
        Replicas: {{$INITIAL_NODE_COUNT}}
- name: Waiting for nodes and pods to be scaled down
  measurements:
  - Identifier: WaitForRunningDeployments
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
  - Identifier: WaitForNodes
    Method: WaitForNodes
    Params:
      minDesiredNodeCount: {{SubtractInt $INITIAL_NODE_COUNT $NODE_COUNT_ERROR_MARGIN}}
      maxDesiredNodeCount: {{AddInt $INITIAL_NODE_COUNT $NODE_COUNT_ERROR_MARGIN}}
      timeout: {{$OPERATION_TIMEOUT}}

- name: Deleting deployments, configmaps
  phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: 0
    tuningSet: QpsTuningSet
    objectBundle:
    - basename: deployment
      objectTemplatePath: deployment.yaml
    - basename: configmap
      objectTemplatePath: configmap.yaml
- name: Waiting for pods/nodes to be deleted
  measurements:
  - Identifier: WaitForRunningDeployments
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
  - Identifier: WaitForNodes
    Method: WaitForNodes
    Params:
      minDesiredNodeCount: {{SubtractInt .Nodes $NODE_COUNT_ERROR_MARGIN}}
      maxDesiredNodeCount: {{AddInt .Nodes $NODE_COUNT_ERROR_MARGIN}}
      timeout: {{$OPERATION_TIMEOUT}}

- name: Collecting measurements
  measurements:
  - Identifier: APIResponsivenessPrometheusSimple
    Method: APIResponsivenessPrometheus
    Params:
      action: gather
      enableViolations: true
      useSimpleLatencyQuery: true
  - Identifier: InClusterNetworkLatency
    Method: InClusterNetworkLatency
    Params:
      action: gather
  - Identifier: DnsLookupLatency
    Method: DnsLookupLatency
    Params:
      action: gather
  - Identifier: TestMetrics
    Method: TestMetrics
    Params:
      action: gather
      systemPodMetricsEnabled: true
      restartCountThresholdOverrides: {{YamlQuote $RESTART_COUNT_THRESHOLD_OVERRIDES 4}}
      enableRestartCountCheck: true
  - Identifier: Quotas total usage
    Method: GenericPrometheusQuery
    Params:
      action: gather
      metricName: Quota usage
      metricVersion: v1
      prometheusClient: managed
      unit: QPMs
      dimensions:
      - quota_metric
      queries:
      - name: perc99
        query: quantile_over_time(0.99, sum by (quota_metric) (irate(serviceruntime_googleapis_com:quota_rate_net_usage{monitored_resource="consumer_quota"}[1m]))[%v:]) * 60
      - name: max
        query: max_over_time(sum by (quota_metric) (irate(serviceruntime_googleapis_com:quota_rate_net_usage{monitored_resource="consumer_quota"}[1m]))[%v:]) * 60
