{{$mountConfigMap := DefaultParam .MountConfigMap false}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    group: spotify
    svc: svc-{{.Name}}
spec:
  replicas: {{RandIntRange .ReplicasMin .ReplicasMax}}
  selector:
    matchLabels:
      name: {{.Name}}
  template:
    metadata:
      labels:
        group: spotify
        name: {{.Name}}
        svc: svc-{{.Index}}
    spec:
      containers:
      - image: k8s.gcr.io/pause:3.1
        name: {{.Name}}
        resources:
          requests:
            cpu: 10m
            memory: "10M"
        volumeMounts:
          # every 6th xxx deployment will have ConfigMap
          {{if and $mountConfigMap (eq (Mod .Index 6) 0) }}
          - name: configmap
            mountPath: /var/configmap
          {{end}}
          - name: secret
            mountPath: /var/secret
      - image: k8s.gcr.io/pause:3.1
        name: {{.Name}}-second
      dnsPolicy: Default
      terminationGracePeriodSeconds: 1
      # Add not-ready/unreachable tolerations for 15 minutes so that node
      # failure doesn't trigger pod deletion.
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
      volumes:
        # every 6th xxx deployment will have ConfigMap
        {{if and $mountConfigMap (eq (Mod .Index 6) 0) }}
        - name: configmap
          configMap:
            name: {{.BaseName}}-{{.Index}}
        {{end}}
        - name: secret
          secret:
            secretName: {{.BaseName}}-{{.Index}}
